Repository SAP-docs/btp-business-application-studio, pull requests merged in 2021-10, with the labels that each got.

#95 Update Adding_an_Existing_Project_Using_Git_Remote_0930e56.md
  docs/Adding_an_Existing_Project_Using_Git_Remote_0930e56.md
Labels: type/spelling-grammar

#111 Update Working_in_the_Dev_Space_Manager_ad40d52.md
  docs/Working_in_the_Dev_Space_Manager_ad40d52.md
Labels: type/content-gaps

#109 Incorrect name of the control
  docs/SAPUI5_Controls_Supported_in_the_Layout_Editor_c5d123e.md
Labels: type/outdated

#59 Update SAP_Fiori_354f00c.md
  docs/SAP_Fiori_354f00c.md
Labels: type/spelling-grammar
